---
kind: pipeline
name: default

steps:
- name: test
  image: golang:1.11
  commands:
  - go test
  
- name: build
  image: golang:1.11
  commands:
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o main .
  when:
    event:
    - push
    - tag
  
- name: publish
  image: plugins/docker
  settings:
    repo: jones2026/go-hello-world
    cache_from: jones2026/go-hello-world:latest
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
